# The URL the site will be built for
base_url = "https://rijkt.link"
theme = "linkita"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[[taxonomies]]
name = "tags"
feed = true
paginate_by = 5

[extra]
# Put all your custom variables here
header_menu_name = "nav"

mermaid = true

[extra.menus]
nav = [
  { url = "$BASE_URL/blog/", name = "Archive" },
  { url = "$BASE_URL/tags/", name = "Tags" },
  { url = "$BASE_URL/about/", name = "About" },
]

[extra.profiles.rijkt]

# The URL of avatar.
# e.g. "icons/github.svg"
avatar_url = "profile_400_400.jpg"

# A description of what is in the avatar.
avatar_alt = ""

# Invert avatar color in dark mode.
# Default value: false
avatar_invert = false

# Profile name.
# Default value: the username
name = "rijkt"

# Profile bio.
# Supports Markdown.
bio = "Passionate about making things easier"

# Social icons.
# "name" should be the file name of "static/icons/*.svg" or
# the icon name of https://simpleicons.org/
# "url" supports "$BASE_URL".
# Other variables: "urls", "title", "titles".
social = [
    { name = "bluesky", url = "https://bsky.app/profile/rijkt.link" },
    { name = "github", url = "https://github.com/rijkt" },
    { name = "email", url = "mailto:pascal@rijkt.link" },
    { name = "rss", url = "$BASE_URL/atom.xml" },
]